[tool.poetry]
name = "insta-mail"
version = "0.1.0"
description = "Backend of project insta-mail."
authors = ["raigordeng <mc.deng@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = {extras = ["standard"], version = "^0.115.8"}
selenium = "^4.29.0"
loguru = "^0.7.3"
pytest = "^8.3.5"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
